-- MySQL Script generated by MySQL Workbench
-- Mon Mar 23 14:31:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `bancos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancos` (
  `idbanco` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `direccion` VARCHAR(200) NULL,
  `telefono` VARCHAR(50) NULL,
  PRIMARY KEY (`idbanco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes` (
  `idcliente` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `direccion` VARCHAR(150) NULL,
  `ruc` VARCHAR(20) NULL,
  `telefono` VARCHAR(50) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Ruc_UNIQUE` ON `clientes` (`ruc` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cheques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cheques` (
  `nrocheque` INT NOT NULL,
  `idbanco` INT NOT NULL,
  `nrocuenta` VARCHAR(30) NULL,
  `fec_emision` DATE NOT NULL,
  `fec_pago` DATE NULL,
  `importe` DOUBLE NOT NULL DEFAULT 0,
  `aordende` VARCHAR(150) NULL,
  `idcliente` INT NOT NULL,
  `tipo` CHAR NOT NULL DEFAULT 'C',
  PRIMARY KEY (`nrocheque`, `idbanco`),
  CONSTRAINT `fk_cheques_bancos1`
    FOREIGN KEY (`idbanco`)
    REFERENCES `bancos` (`idbanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cheques_clientes1fk_cheques_clientes1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `clientes` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cheques_bancos1_idx` ON `cheques` (`idbanco` ASC) VISIBLE;

CREATE INDEX `fk_cheques_clientes1_idx` ON `cheques` (`idcliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estado` (
  `idestado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `operaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `operaciones` (
  `idoperaciones` INT NOT NULL,
  `fec_operacion` DATE NOT NULL,
  `idestado` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `observacion` VARCHAR(250) NULL,
  PRIMARY KEY (`idoperaciones`),
  CONSTRAINT `fk_operaciones_clientes1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `clientes` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operaciones_estado1`
    FOREIGN KEY (`idestado`)
    REFERENCES `estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_operaciones_clientes1_idx` ON `operaciones` (`idcliente` ASC) VISIBLE;

CREATE INDEX `fk_operaciones_estado1_idx` ON `operaciones` (`idestado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cheque_operacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cheque_operacion` (
  `idcheque_operacion` INT NOT NULL AUTO_INCREMENT,
  `idoperaciones` INT NOT NULL,
  `nrocheque` INT NOT NULL,
  `idbanco` INT NOT NULL,
  PRIMARY KEY (`idcheque_operacion`),
  CONSTRAINT `fk_cheque_operacion_operaciones`
    FOREIGN KEY (`idoperaciones`)
    REFERENCES `operaciones` (`idoperaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cheque_operacion_cheques1`
    FOREIGN KEY (`cheques_nrocheque`)
    REFERENCES `cheques` (`nrocheque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cheque_operacion_operaciones_idx` ON `cheque_operacion` (`idoperaciones` ASC) VISIBLE;

CREATE UNIQUE INDEX `idoperaciones_UNIQUE` ON `cheque_operacion` (`idoperaciones` ASC) VISIBLE;

CREATE INDEX `fk_cheque_operacion_cheques1_idx` ON `cheque_operacion` (`cheques_nrocheque` ASC, `cheques_codbanco` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `respaldos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `respaldos` (
  `idrespado` INT NOT NULL AUTO_INCREMENT,
  `idoperacion` INT NOT NULL,
  `nrocheque` INT NOT NULL,
  `idbanco` INT NOT NULL,
  `importe` DOUBLE NOT NULL DEFAULT 0,
  PRIMARY KEY (`idrespado`),
  CONSTRAINT `fk_respaldos_cheque_operacion1`
    FOREIGN KEY (`idoperacion`)
    REFERENCES `cheque_operacion` (`idcheque_operacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respaldos_cheques1`
    FOREIGN KEY (`nrocheque` , `idbanco`)
    REFERENCES `cheques` (`nrocheque` , `idbanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_respaldos_cheque_operacion1_idx` ON `respaldos` (`idoperacion` ASC) VISIBLE;

CREATE INDEX `fk_respaldos_cheques1_idx` ON `respaldos` (`nrocheque` ASC, `idbanco` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
